// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PokemonBattle struct {
	ID       uuid.UUID
	Pokemon1 string
	Pokemon2 string
	Winner   pgtype.Text
}
