// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	GetPokeBattlesByPokemon(ctx context.Context, arg GetPokeBattlesByPokemonParams) ([]PokemonBattle, error)
}

var _ Querier = (*Queries)(nil)
