// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePokeBattle(ctx context.Context, arg CreatePokeBattleParams) (PokemonBattle, error)
	GetPokeBattle(ctx context.Context, id uuid.UUID) (PokemonBattle, error)
	ListPokeBattles(ctx context.Context, arg ListPokeBattlesParams) ([]PokemonBattle, error)
}

var _ Querier = (*Queries)(nil)
