// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: rpc_poke_stats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokeStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon string `protobuf:"bytes,1,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
}

func (x *PokeStatsRequest) Reset() {
	*x = PokeStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_poke_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokeStatsRequest) ProtoMessage() {}

func (x *PokeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_poke_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokeStatsRequest.ProtoReflect.Descriptor instead.
func (*PokeStatsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_poke_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PokeStatsRequest) GetPokemon() string {
	if x != nil {
		return x.Pokemon
	}
	return ""
}

type PokeStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon string  `protobuf:"bytes,1,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Wins    int64   `protobuf:"varint,2,opt,name=wins,proto3" json:"wins,omitempty"`
	Loses   int64   `protobuf:"varint,3,opt,name=loses,proto3" json:"loses,omitempty"`
	Winrate float32 `protobuf:"fixed32,4,opt,name=winrate,proto3" json:"winrate,omitempty"`
}

func (x *PokeStatsResponse) Reset() {
	*x = PokeStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_poke_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokeStatsResponse) ProtoMessage() {}

func (x *PokeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_poke_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokeStatsResponse.ProtoReflect.Descriptor instead.
func (*PokeStatsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_poke_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PokeStatsResponse) GetPokemon() string {
	if x != nil {
		return x.Pokemon
	}
	return ""
}

func (x *PokeStatsResponse) GetWins() int64 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *PokeStatsResponse) GetLoses() int64 {
	if x != nil {
		return x.Loses
	}
	return 0
}

func (x *PokeStatsResponse) GetWinrate() float32 {
	if x != nil {
		return x.Winrate
	}
	return 0
}

var File_rpc_poke_stats_proto protoreflect.FileDescriptor

var file_rpc_poke_stats_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x6f,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x22, 0x71, 0x0a, 0x11, 0x50, 0x6f, 0x6b, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x6f, 0x73, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x72, 0x61, 0x74, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_poke_stats_proto_rawDescOnce sync.Once
	file_rpc_poke_stats_proto_rawDescData = file_rpc_poke_stats_proto_rawDesc
)

func file_rpc_poke_stats_proto_rawDescGZIP() []byte {
	file_rpc_poke_stats_proto_rawDescOnce.Do(func() {
		file_rpc_poke_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_poke_stats_proto_rawDescData)
	})
	return file_rpc_poke_stats_proto_rawDescData
}

var file_rpc_poke_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_poke_stats_proto_goTypes = []interface{}{
	(*PokeStatsRequest)(nil),  // 0: pb.PokeStatsRequest
	(*PokeStatsResponse)(nil), // 1: pb.PokeStatsResponse
}
var file_rpc_poke_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_poke_stats_proto_init() }
func file_rpc_poke_stats_proto_init() {
	if File_rpc_poke_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_poke_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokeStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_poke_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokeStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_poke_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_poke_stats_proto_goTypes,
		DependencyIndexes: file_rpc_poke_stats_proto_depIdxs,
		MessageInfos:      file_rpc_poke_stats_proto_msgTypes,
	}.Build()
	File_rpc_poke_stats_proto = out.File
	file_rpc_poke_stats_proto_rawDesc = nil
	file_rpc_poke_stats_proto_goTypes = nil
	file_rpc_poke_stats_proto_depIdxs = nil
}
