// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: service_poke_stats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_poke_stats_proto protoreflect.FileDescriptor

var file_service_poke_stats_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x14,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x32, 0x48, 0x0a, 0x09, 0x50, 0x6f, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x6b,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_service_poke_stats_proto_goTypes = []interface{}{
	(*PokeStatsRequest)(nil),  // 0: pb.PokeStatsRequest
	(*PokeStatsResponse)(nil), // 1: pb.PokeStatsResponse
}
var file_service_poke_stats_proto_depIdxs = []int32{
	0, // 0: pb.PokeStats.GetPokeStats:input_type -> pb.PokeStatsRequest
	1, // 1: pb.PokeStats.GetPokeStats:output_type -> pb.PokeStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_poke_stats_proto_init() }
func file_service_poke_stats_proto_init() {
	if File_service_poke_stats_proto != nil {
		return
	}
	file_rpc_poke_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_poke_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_poke_stats_proto_goTypes,
		DependencyIndexes: file_service_poke_stats_proto_depIdxs,
	}.Build()
	File_service_poke_stats_proto = out.File
	file_service_poke_stats_proto_rawDesc = nil
	file_service_poke_stats_proto_goTypes = nil
	file_service_poke_stats_proto_depIdxs = nil
}
